title: Hello, world! I'm Nirmalya...
description: > # this means to ignore newlines until "baseurl:"
  This is my personal blog site in github.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
# baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Nirmalya Dey # add your name
author-img: my_git.jpg # add your photo
about-author: I am a software delveloper. I love to design robust framework... # add description
# social-twitter: # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: nirmalya123 # add your Github handle
social-wordpress: nirmalya-blog
#social-linkedin: # add your Linkedin handle
social-email: nirmalya.do@gmail.com

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
# analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
